steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    '${_GCP_REGION}-docker.pkg.dev/$_GCP_PROJECT_ID/${_ARTIFACT_REPO_NAME}/${_IMAGE_NAME}',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    '${_GCP_REGION}-docker.pkg.dev/$_GCP_PROJECT_ID/${_ARTIFACT_REPO_NAME}/${_IMAGE_NAME}',
  ]
substitutions:
  _GCP_PROJECT_ID: "default" # default
  _GCP_REGION: "default" # default
  _ARTIFACT_REPO_NAME: "default" # default
  _IMAGE_NAME: "default" # default
images:
- '${_GCP_REGION}-docker.pkg.dev/$_GCP_PROJECT_ID/${_ARTIFACT_REPO_NAME}/${_IMAGE_NAME}'
