apiVersion: apps/v1
kind: Deployment
metadata:
  name: stt-ws-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stt-ws-server
  template:
    metadata:
      labels:
        app: stt-ws-server
    spec:
      containers:
        - name: stt-ws-server
          image: "${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/${ARTIFACT_REPO_NAME}/${APP_NAME}"
          ports:
            - containerPort: 7777

---
apiVersion: v1
kind: Service
metadata:
  name: stt-ws-server-service
spec:
  selector:
    app: stt-ws-server
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
  type: LoadBalancer
